spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://k9c105.p.ssafy.io:3306/kkalong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kkalong
    password: c105ssafykkalong
  data:
    mongodb:
      uri: mongodb://admin:c105ssafykkalong@k9c105.p.ssafy.io:27017/kkalong
    redis:
      host: k9c105.p.ssafy.io
      port: 6379
      password: c105ssafykkalong

  security:
    user:
      name: ssafy
      password: ssafy
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
      file-size-threshold: 0

springdoc:
  packages-to-scan: com.ssafy.kkalong
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /kkalong-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    api-docs:
      path: /api-docs/json
      groups:
        enabled: true
    cache:
      disabled: true

logging.level:
  org.hibernate:
    SQL: debug
    type: trace

server:
  port: 8761

jwt:
  secret-key: Sfi49D0N1Gqo10bPgUyTFsRMkJpGLXSvGP0UJN56EB30r5TcrtlSXfQ7TndvYjNvfkEKLqILn0j1SmKODOSDSF098BBgI3nVPEahqxeY8qbPSFGyzyEVxnl4AQcrnVneI
  expiration-minutes: 30
  refresh-expiration-hours: 24
  issuer: ssafy

cloud:
  aws:
    credentials:
      instance-profile: false
      access-key: AKIA5RRQZSI64T25QVH5
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

aws:
  s3:
    bucket: kkalong

ai-server:
  gpu:
    ip: http://222.107.238.44
    preprocess-port: 4050
    viton-port: 4051
  openpose: http://118.222.223.6:4052
